version: 2.1

jobs:

  build:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run: 
          name: Docker login 
          command: |
            echo "$QUAY_PASS" | docker login quay.io -u "$QUAY_USER" --password-stdin

      - run: 
          name: Build image
          command: |
            docker build -t quay.io/$QUAY_USER/my-image:latest .  

      - run: 
          name: Push image
          command: |
            docker tag -t my-image:latest quay.io/$QUAY_USER/myrepo
            docker push quay.io/$QUAY_USER/myrepo         



workflows:
  build_and_test:
    jobs:
      - build
