version: 2.1

jobs:

  build:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout

      # - setup_remote_docker:
      #     version: 19.03.13
      #     docker_layer_caching: true

      - run: 
          name: Docker login 
          command: |
            echo "$QUAY_USER" | docker login quay.io -u "$QUAY_PASS" --password-stdin

      # - run: 
      #     name: Build image
      #     command: |
      #       docker build -t first_build:0.1 .   

      # - run: 
      #     name: Push image
      #     command: |
      #       docker tag first_build:0.1 gowri45/vasu_2511  
      #       docker push gowri45/vasu_2511          
      

workflows:
  build_and_test:
    jobs:
      - build
